version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: contacts
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db_data:/var/lib/mysql 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8080:80

volumes:
  db_data: 